#!/usr/bin/env bash
# Bake a short audio clip (mp3/wav — anything ffmpeg reads) into voice.h,
# the charge-complete voice announcement:
#
#   tools/make_voice.sh ~/Downloads/clip.mp3          # mastered (default)
#   tools/make_voice.sh ~/Downloads/clip.mp3 --raw    # straight convert
#
# voice.h is GITIGNORED — personal audio stays local, like secrets.h; a
# build without it falls back to the stock chirp alert, so public/webflash
# images stay neutral. 16 kHz mono s16le keeps a ~4 s line near 120 KB of
# flash (the app partition has megabytes to spare).
#
# The default mastering chain is voiced for the tiny bare speaker these
# panels drive (a straight convert sounds tinny on one): drop everything
# below 150 Hz (the cone can't make it — it only wastes excursion and
# distorts), +4 dB body at 300 Hz, -3 dB at the 4.5 kHz harshness band,
# roll off above 6.8 kHz, then 3:1 compression + a 0.95 limiter for a
# fuller, steadier level. Pass --raw to skip it.
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
IN="${1:?usage: tools/make_voice.sh <clip.mp3|.wav> [--raw]}"
command -v ffmpeg >/dev/null || { echo "✗ ffmpeg not found (brew install ffmpeg)"; exit 1; }

FILTER="highpass=f=150,equalizer=f=300:t=q:w=1.0:g=4,equalizer=f=4500:t=q:w=1.5:g=-3,lowpass=f=6800,acompressor=threshold=-18dB:ratio=3:attack=8:release=120:makeup=6dB,alimiter=limit=0.95"
[ "${2:-}" = "--raw" ] && FILTER="anull"

TMP="$(mktemp -t voice_pcm)"
trap 'rm -f "$TMP"' EXIT
ffmpeg -v error -y -i "$IN" -af "$FILTER" -ac 1 -ar 16000 -f s16le -acodec pcm_s16le "$TMP"

BYTES="$(wc -c < "$TMP" | tr -d ' ')"
{
  echo "#pragma once"
  echo "#include <stdint.h>"
  echo "// Generated by tools/make_voice.sh from \"$(basename "$IN")\" — do not edit."
  echo "// 16000 Hz mono s16le PCM, $BYTES bytes (~$((BYTES / 32000)) s)."
  echo "constexpr uint32_t kVoiceRate = 16000;"
  echo "const unsigned char kVoicePcm[] = {"
  xxd -i < "$TMP"
  echo "};"
  echo "const unsigned int kVoicePcmLen = sizeof(kVoicePcm);"
} > "$HERE/voice.h"
echo "==> voice.h ($((BYTES / 1024)) KB of PCM, ~$((BYTES / 32000)) s)"
